// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:a6ee4e87-30c3-4a53-9716-67d80a8a119a",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_rqUZw06b4",
    "aws_user_pools_web_client_id": "26oabapt2vdf9hdnhu4ar7tj05",
    "aws_appsync_graphqlEndpoint": "https://yskrcuw63vh5xbt6jp7uututvq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
